version: '3.8'

volumes:
  postgresql_db_vol:
  pgadmin_vol:


networks:
  default:
    name: network_kubenews

services:

  app:
    image: fernandord/kube-news:v1
    container_name: app_kubenews
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql_db
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubeuser 
      DB_PASSWORD: kubepass
      DB_HOST: postgresql_db

  postgresql_db:
    container_name: postgresql_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: faz_certo_que_da_certo
    ports:
      - 5432:5432
    volumes:
      - postgresql_db_vol:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: faz_certo_que_da_certo
    ports:
      - 5050:80
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
      - pgadmin_vol:/certs/server.cert
      - pgadmin_vol:/certs/server.key
      - pgadmin_vol:/servers.json
   